### ISSUE TITLE
Rebuild strips image values and uses defaults.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#161] opened 2019-02-28 00:32 UTC
Pressing the rebuild button in the CMP strips image values from all pages.

Say I have an image tag like:
```
<img src="/assets/themes/site/images/press-default-image.jpg" data-fred-name="single-column-image" data-fred-image-media-source="Media">
```
After a rebuild, if logged out of Fred, all images will now be showing what's in the `src` attribute instead of what's been applied in Fred.

If you're logged into Fred, images display correctly and you can manually fix it by loading each page separately and then saving it.

**Comment by theboxer** [comment] 2019-02-28 16:52
I can't reproduce this one, it probably got fixed in past commits.

Any chance you could try against the current master branch? Or I can try and build you alpha version...

**Comment by digitalpenguin** [comment] 2019-03-06 03:09
Sorry I haven't had a chance to test it with the latest branch yet.
Is anyone able to replicate this on 1.0.0-pl?

**Comment by digitalpenguin** [comment] 2019-03-20 14:07
@theboxer I have a site I can give you access to where it's happening if you like?

**Comment by theboxer** [comment] 2019-03-20 15:31
Here's the alpha release of 1.1.0 - https://github.com/modxcms/fred/blob/master/_packages/fred-1.1.0-alpha.transport.zip you can test it against your setup.

I wouldn't recommend installing that on live though, there are still few bugs I bet.

**Comment by digitalpenguin** [comment] 2019-03-20 15:53
Brilliant, thanks. I'll get to testing this tomorrow.

**Comment by digitalpenguin** [comment] 2019-03-21 04:35
Happy to report this appears to be fixed in the 1.1.0 alpha version! :D
Thanks very much @theboxer !

There's a little bit of weirdness going on in the console output when rebuilding but doesn't seem to affect anything.

Console running...
Refreshing Resource ID 72
Rebuild Completed
Refreshing Resource ID 1
Refreshing Resource ID 6
PHP notice: Undefined index: rightcollinks
PHP notice: Undefined index: leftcollinks
Refreshing Resource ID 8
Refreshing Resource ID 9
Refreshing Resource ID 12
Refreshing Resource ID 13
Refreshing Resource ID 14
Refreshing Resource ID 15
Refreshing Resource ID 16
Refreshing Resource ID 17
Refreshing Resource ID 94
Refreshing Resource ID 95
Refreshing Resource ID 10
PHP notice: Undefined index: rightcollinks
PHP notice: Undefined index: leftcollinks
Refreshing Resource ID 2
Refreshing Resource ID 3
Refreshing Resource ID 4
Refreshing Resource ID 5
Refreshing Resource ID 11
Refreshing Resource ID 20
Refreshing Resource ID 22
Refreshing Resource ID 23
Refreshing Resource ID 24
Refreshing Resource ID 25
Refreshing Resource ID 26
Refreshing Resource ID 27
Refreshing Resource ID 28
PHP notice: Undefined index: social-media-icons
Refreshing Resource ID 29
Refreshing Resource ID 30
Refreshing Resource ID 31
Refreshing Resource ID 32
Refreshing Resource ID 33
Refreshing Resource ID 34
Refreshing Resource ID 53
Refreshing Resource ID 54
Refreshing Resource ID 55
Refreshing Resource ID 19
Refreshing Resource ID 40
Refreshing Resource ID 41
Refreshing Resource ID 42
Refreshing Resource ID 70
Refreshing Resource ID 73
Refreshing Resource ID 74
Refreshing Resource ID 75
Refreshing Resource ID 76
Refreshing Resource ID 77
Refreshing Resource ID 78
Refreshing Resource ID 79
Refreshing Resource ID 80
Refreshing Resource ID 81
Refreshing Resource ID 82
Refreshing Resource ID 83
Refreshing Resource ID 84
Refreshing Resource ID 85
Refreshing Resource ID 86
Refreshing Resource ID 87
Refreshing Resource ID 88
Refreshing Resource ID 89
Refreshing Resource ID 90
Refreshing Resource ID 91
Refreshing Resource ID 92
Refreshing Resource ID 93
Refreshing Resource ID 18
Refreshing Resource ID 47
Refreshing Resource ID 48
Refreshing Resource ID 43
Refreshing Resource ID 44
Refreshing Resource ID 45
Refreshing Resource ID 49
Refreshing Resource ID 58
Refreshing Resource ID 71
Refreshing Resource ID 72
Rebuild Completed

**Comment by digitalpenguin** [comment] 2019-03-21 04:37
Feel free to close this when you see it. I've left it open in case you want to tag a specific PR or something. Thanks!

**Comment by rthrash** [comment] 2019-05-09 14:46
Thanks @digitalpenguin

**Closed by rthrash** 2019-05-09 14:46 UTC
