### ISSUE TITLE
Feature Request: Support Static Sources for FRED Elements and Option Sets

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#225] opened 2019-05-21 07:51 UTC
I am losing a lot of time copy pasting FRED Elements and Option Sets code from my editor to FRED...
Would be great if this would be a static file.

**Comment by theboxer** [comment] 2019-05-21 09:41
Duplicate of #180

**Closed by theboxer** 2019-05-21 09:41 UTC
