### ISSUE TITLE
Blank Calendar month dropdown

### ISSUE THREAD

**Issue by alienbuild** [modxcms/fred#255] opened 2019-06-24 20:37 UTC
## Subject of the issue
Toggling the publishedon calendar and going to choose a month displays blank options (white text).

## Your environment
PHP 7.1
MODX 3 (clean install)

## Steps to reproduce
Click settings -> advanced settings -> publishedon

![calendar-issue](https://user-images.githubusercontent.com/32590877/60050310-3a76ca80-96c8-11e9-8edd-cc1ec196cf85.jpg)

**Comment by rthrash** [comment] 2019-06-27 17:46
Have you tested this without MODX 3? Which version of Fred was this? Browser?

**Comment by rthrash** [comment] 2019-06-28 17:49
With the current master branch, it looks like this for me:

<img width="160" alt="Meet Fred, The Friendly Editor for MODX 2019-06-28 12-48-23" src="https://user-images.githubusercontent.com/234237/60361168-26bab500-99a3-11e9-9f1f-4d7a55a33bcd.png">

Are you still having issues with it on your end?

**Comment by alienbuild** [comment] 2019-06-30 10:40
I was using latest stable version of MODX 2.7.1 and the latest beta release, both clean installs. Haven't tested it with the latest commit since the build though.

**Comment by rthrash** [comment] 2019-07-02 20:22
Going to close this since we can't reproduce this. Please reopen if you can reproduce after the first 1.1 RC which should be out in the next 24-48 hours at https://github.com/modxcms/fred/releases. Thanks!

**Closed by rthrash** 2019-07-02 20:22 UTC
Labels: bug
