### ISSUE TITLE
Changing page alias from fred results in Not Found 404 error

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#302] opened 2019-09-02 10:36 UTC
Hi,

When changing alias from the Settings pane on Fred, it will result on a 404 page instead of redirecting to the new alias after saving.
![image](https://user-images.githubusercontent.com/22750391/64108805-c61a7080-cd75-11e9-9382-a8c2159a9c69.png)

**Comment by JANogueira** [comment] 2019-09-02 10:36
Forgot to mention:
Modx 2.7.1-pl
Fred 1.1.0-pl

**Comment by theboxer** [comment] 2019-09-02 12:18
I can't reproduce this. I'm getting a redirect every time I change the alias field...

**Comment by JANogueira** [comment] 2019-09-02 13:20
I will try to reproduce on other instance at the end of day and I will share the result.

**Comment by JANogueira** [comment] 2019-09-02 13:34
I can now understand what happens.
It indeed reloads after you change the alias, but on the address bar remains unchanged. If you press F5, the page won't exist.

I was able to see this on a WebHosting space with Cpanel and on my local PC. But on another server running CentOS CWP, it refuses to reload the page if the address bar does not match.

How to reproduce?
Enable FRULs, create like a resource tree so you can have mysite.com/company/about/

Change the alias about to about1. Page will reload, but the address bar URL will remain unchanged. If you press F5, it will give you a 404. On the servers that are forcing page reload on the HTTP headers with different request address than the URL, this results in a 404.

**Comment by theboxer** [comment] 2019-09-02 14:03
Nope, can't reproduce. Have URL: http://pkgs.modx.local/modx/fred-x/child.html and change alias to `child-x` and it redirects correctly to `http://pkgs.modx.local/modx/fred-x/child-x.html` and the URL changes as well.

**Comment by JANogueira** [comment] 2019-09-02 14:13
Spotted one difference from your links when compared to mine.
I removed HTML extension from the content types. Not sure if there's a relation:
![image](https://user-images.githubusercontent.com/22750391/64120467-32a46800-cd94-11e9-8821-dc512b8c6951.png)

**Comment by theboxer** [comment] 2019-09-02 14:18
nope, still works

**Comment by JANogueira** [comment] 2019-09-02 14:23
ok, I will have to try it with a new fresh installation to confirm if it is reated with my two projects or not. Sorry for wasting your time.

I will share my feedback by the end of the day.

**Comment by JANogueira** [comment] 2019-09-02 17:28
Hi John,

Here you will see what I was trying to explain. My URL does not change properly. It is one step late:
![fred-alias-reproduction](https://user-images.githubusercontent.com/22750391/64128657-79ec2200-cdaf-11e9-8088-5e07e438f7de.gif)

**Comment by theboxer** [comment] 2019-09-02 20:40
yeah, no idea why it doesn't work for you. I just tried firefox and it works fine...

**Comment by JANogueira** [comment] 2019-09-02 20:46
This happening the same thing on all my browsers and on a cPanel webhosting. Same behavior.

Can I be missing a php module or an Apache extension?

Thanks again

**Comment by theboxer** [comment] 2019-09-02 20:48
I don't think so, the redirect is handled purely in JavaScript

**Comment by JANogueira** [comment] 2019-09-02 20:50
Well, last question before I close this issue:
Is there any test or debug that I can do for you?

Thanks again

**Comment by theboxer** [comment] 2019-09-02 20:51
Email me credentials to your site to john@modx.com I'll take a peek when I'll have time tomorrow.

**Comment by JANogueira** [comment] 2019-09-02 20:55
Ok many thanks John

**Comment by theboxer** [comment] 2019-09-03 14:44
Resolved (it's fixed on your site + it'll be included in 1.1.1). Thank you

**Closed** 2019-09-03 14:44 UTC
Labels: bug

**Comment by JANogueira** [comment] 2019-09-03 14:46
Thank You very much John!
Cheers
