### ISSUE TITLE
utf8mb4 support

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#247] opened 2019-06-17 09:55 UTC
Some console errors when installing 1.1.0-beta2 with utf8mb4: 

```
Error altering field FredBlueprintCategory->name: Array ( [0] => HY000 [1] => 1709 [2] => Index column size too large. The maximum column size is 767 bytes )

Error altering field FredBlueprint->name: Array ( [0] => HY000 [1] => 1709 [2] => Index column size too large. The maximum column size is 767 bytes )

Error altering field FredElementCategory->name: Array ( [0] => HY000 [1] => 1709 [2] => Index column size too large. The maximum column size is 767 bytes )

Error altering field FredElement->name: Array ( [0] => HY000 [1] => 1709 [2] => Index column size too large. The maximum column size is 767 bytes )

Error altering field FredTheme->name: Array ( [0] => HY000 [1] => 1709 [2] => Index column size too large. The maximum column size is 767 bytes )
```

**Comment by theboxer** [comment] 2019-06-17 10:16
Duplicate of #239

**Closed by theboxer** 2019-06-17 10:16 UTC
