### ISSUE TITLE
Path to images wrong

### ISSUE THREAD

**Issue by lottaar** [modxcms/fred#499] opened 2024-05-23 05:04 UTC
There is an issue with newly uploaded images in the image browser.

1. The image thumbnail doesn't show a preview of the image.
2. When selecting the image the first letter of the path to the image is missing, so the link to the image is broken.

Note that it's only an issue when you first upload the image. When you go back the preview is shown and the path after selecting the image is correct.

Fred 2.2.3
MODX 3.0.5

**Comment by modxcommunity** [comment] 2024-06-07 12:13
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/fred-image-tv-mangling-url-after-saving/7809/2

**Comment by matdave** [comment] 2024-06-13 19:23
The comment from the community is unrelated. That is related to an issue with the deprecated 2.x branch version.

**Comment by lottaar** [comment] 2024-09-20 06:23
Any updates? Still the same issue in freshly installed MODX 3.0.5 and Fred 3.0.2.

**Comment by matdave** [comment] 2024-09-30 22:42
I finally found it the cause of the issue (sort of). I've got a workaround coded into it and it will be part of the next release.

**Comment by lottaar** [comment] 2024-10-01 04:19
Awesome!

**Closed** 2024-10-22 16:32 UTC
