### ISSUE TITLE
How to restrict fred elements to specific contexts, users or user groups?

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#292] opened 2019-08-15 15:54 UTC
Hi,

Is there any way to allow restriction of Fred elements and/or Fred categories to Modx contexts, specific users or specific user groups?

One of the objectives would be to have different level of permissions for specific content editors (like one user or user group with more privileges, and other with simplified privileges).

Other use case for the context restriction would be to create multiple sites in one Manager and have different Fred elements per context, allowing separated management.
One example would be a site www.site.com (having specific fred elements for the web page itself) and newsletter.site.com (having newsletter blocks only for newsletter visual build to be then used by virtuNewsletter, as an example).

Is this planned for future releases?

Thanks in advance

**Comment by theboxer** [comment] 2019-08-15 15:56
Duplicate of #80

**Closed by theboxer** 2019-08-15 15:56 UTC

**Comment by JANogueira** [comment] 2019-08-15 15:58
Thanks John. I was looking on the closed issues but didn't find this one.
Cheers
