### ISSUE TITLE
Remove fade-out transition on "mouse out" when hovering over elements

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#178] opened 2019-03-21 03:47 UTC
Fred can feel quite sluggish due to the transition effects when moving the mouse over an array of elements. 
It would feel much faster if the moment the mouse moved away from an element, the selection immediately disappeared. 

Currently we need to wait for the element to deselect and then wait for the new element to select.

Personally I'd prefer no transition effects at all to make it snappier but just removing the mouse out transition would already make a huge difference ;)

What are you thoughts on this?

**Comment by matdave** [comment] 2019-03-21 17:05
So the issue is that it lead to an aweful experience when you try to click things like the toolbar.  If you go slightly out of the element when heading to the toolbar it would disappear and you would have to re-initiate the element.  It's not really a CSS transition that is delaying things, it is a hover intent script that is delaying and making sure you are intentionally leaving.

We can play with the timings again, but after using Fred without it for a while, it was a much better experience to have a delay.

**Comment by digitalpenguin** [comment] 2019-03-22 00:54
Ah I see. Hmmm yeah I can imagine the amount of trial and error that's gone into getting it this good already. 
Just to make things complicated... what about it there was a slightly extended safe space / buffer zone around the toolbar itself where it stays selected for the current amount of time, but further away it immediately deselects? I doubt it would be simple so take that with a grain of salt. :)

**Comment by matdave** [comment] 2019-05-13 13:02
I'm going to close this for now as we'll be reworking the toolbar in the future.

**Closed by matdave** 2019-05-13 13:02 UTC
